services:
  # See https://hub.docker.com/_/postgres for more information
  db:
    image: postgres
    container_name: escalaralcoiaicomtat_backend_db
    environment:
      POSTGRES_PASSWORD: change-me! # This should be modified
      PGUSER: postgres
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
    ports:
      - "5432:5432"

volumes:
  pgdata-dev:
