services:
  backend:
    image: arnyminerz/escalaralcoiaicomtat:1.0-SNAPSHOT
    restart: no
    container_name: escalaralcoiaicomtat_backend
    environment:
      # Configure database
      DATABASE_DRIVER: "org.postgresql.Driver"
      DATABASE_URL: "jdbc:postgresql://db:5432/postgres"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "AbfEwudQ8AqhhVVqTiRURpbMmQTW46"
    networks:
      - escalaralcoiaicomtat_backend
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy

  # See https://hub.docker.com/_/postgres for more information
  db:
    image: postgres
    container_name: escalaralcoiaicomtat_backend_db
    environment:
      POSTGRES_PASSWORD: AbfEwudQ8AqhhVVqTiRURpbMmQTW46 # This should be modified
      PGUSER: postgres
    networks:
      - escalaralcoiaicomtat_backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
